
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sfdfdsodsqqttvvqeuua.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNmZGZkc29kc3FxdHR2dnFldXVhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1OTMzNDcsImV4cCI6MjA2MjE2OTM0N30.k1riP_FEcwZm5R8NbAdW2EojcMBE__iknyAfLAlu9ag";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storage: localStorage
  }
});
